[package]
name = "awaken_pi"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]

[dependencies]
ds323x = "0.2.0"
chrono = "0.4"
linux-embedded-hal = "0.2.1"
runas = "0.1.4"

